# Generated by Django 3.2 on 2021-04-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_id', models.CharField(max_length=20)),
                ('p_img', models.ImageField(upload_to='pics')),
                ('p_contact', models.IntegerField()),
                ('p_dob', models.IntegerField()),
                ('p_age', models.IntegerField()),
                ('p_gender', models.CharField(max_length=10)),
                ('p_diagnosed', models.TextField()),
                ('p_blood', models.FloatField()),
                ('p_rate', models.FloatField()),
                ('p_height', models.FloatField()),
                ('p_weight', models.FloatField()),
                ('p_allergies', models.TextField()),
                ('p_health', models.TextField()),
                ('p_city', models.CharField(max_length=100)),
                ('p_address', models.TextField()),
                ('p_drug', models.CharField(max_length=100)),
                ('p_unit', models.CharField(max_length=200)),
                ('p_dosage', models.CharField(max_length=200)),
            ],
        ),
    ]
