# Generated by Django 3.2 on 2021-04-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='health_prescription',
        ),
    ]
