# Generated by Django 3.2 on 2021-04-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20210426_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_dosage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='p_drug',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='p_unit',
            field=models.TextField(),
        ),
    ]
