# Generated by Django 3.2 on 2021-04-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20210426_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_contact',
            field=models.BigIntegerField(),
        ),
    ]
