# Generated by Django 3.2 on 2021-04-26 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_prescription_p_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='p_currdate',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
