# Generated by Django 3.2 on 2021-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_alter_prescription_p_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_check',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='p_currdate',
            field=models.CharField(max_length=60),
        ),
    ]
