# Generated by Django 3.2 on 2021-04-26 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20210426_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_currdate',
            field=models.IntegerField(default=datetime.date(2021, 4, 26)),
        ),
    ]
