# Generated by Django 3.2 on 2021-04-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_alter_prescription_p_currdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_currdate',
            field=models.CharField(max_length=50),
        ),
    ]
