# Generated by Django 3.2 on 2021-04-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_alter_prescription_p_currdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='p_currdate',
            new_name='p_currdates',
        ),
    ]
