# Generated by Django 3.2 on 2021-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_rename_p_currdate_prescription_p_currdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_currdates',
            field=models.DateField(),
        ),
    ]
