# Generated by Django 3.2 on 2021-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_alter_prescription_p_currdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_name',
            field=models.CharField(max_length=200),
        ),
    ]
