# Generated by Django 3.2 on 2021-04-27 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_prescription_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='current',
        ),
        migrations.AddField(
            model_name='prescription',
            name='p_currdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
