# Generated by Django 3.2 on 2021-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_auto_20210427_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_city',
            field=models.CharField(max_length=200),
        ),
    ]
