# Generated by Django 3.2 on 2021-04-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0019_alter_prescription_p_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
