# Generated by Django 3.2 on 2021-04-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_auto_20210427_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='p_img',
        ),
    ]
