# Generated by Django 3.2 on 2021-04-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0022_remove_prescription_p_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='p_currdate',
        ),
    ]
