# Generated by Django 3.2 on 2021-04-27 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0023_remove_prescription_p_currdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='p_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
