# Generated by Django 3.2 on 2021-04-27 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0026_remove_prescription_p_currdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='p_currdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
