# Generated by Django 3.2 on 2021-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0029_remove_prescription_p_currdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='p_currdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
