# Generated by Django 3.2 on 2021-04-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0034_alter_prescription_p_currdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_dob',
            field=models.CharField(max_length=60),
        ),
    ]
