# Generated by Django 3.2 on 2021-04-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0035_alter_prescription_p_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='p_currdate',
        ),
    ]
