# Generated by Django 3.2 on 2021-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0038_remove_prescription_p_currdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
