# Generated by Django 3.2 on 2021-04-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0039_alter_prescription_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='p_name',
            field=models.CharField(max_length=100),
        ),
    ]
