# Generated by Django 3.2 on 2021-04-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0040_alter_prescription_p_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='p_name',
        ),
    ]
