# Generated by Django 3.2 on 2021-04-27 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0041_remove_prescription_p_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='p_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
